name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Only the last 3 Kubernetes minor versions receive updates:
    - name: v1.17
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.17.14
        build-args: KUBE_VERSION=v1.17.14
    - name: v1.18
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.18.11
        build-args: KUBE_VERSION=v1.18.11
    - name: v1.19
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.19.4
        build-args: KUBE_VERSION=v1.19.4
