name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Only the last 3 Kubernetes minor versions receive updates:
    - name: v1.20
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.20.15
        build-args: KUBE_VERSION=v1.20.15
    - name: v1.21
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.21.12
        build-args: KUBE_VERSION=v1.21.12
    - name: v1.22
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.22.9
        build-args: KUBE_VERSION=v1.22.9
    - name: v1.23
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: incloudhq/kube-deploy:v1.23.6
        build-args: KUBE_VERSION=v1.23.6
