name: ci

on: push
#    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Only the last 3 Kubernetes minor versions receive updates:
    - name: &version1 v1.17.12
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: *version1
        build-args:
        - KUBE_VERSION=*version1
    - name: v1.18.9
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: v1.18.9
        build-args:
          - KUBE_VERSION=v1.18.9
    - name: v1.19.2
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: v1.19.2
        build-args:
          - KUBE_VERSION=v1.19.2
